# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: prometheus-config2
# data:
#   prometheus.yml: |
#     global:
#       scrape_interval: {{ .Values.prometheus.config.scrape_interval | default "15s" }}

#     scrape_configs:
#       - job_name: 'stock_data'
#         metrics_path: '{{ .Values.prometheus.config.metrics_path | default "/metrics/" }}'
#         static_configs:
#           - targets: {{ .Values.prometheus.config.static_configs | toJson }}

#     rule_files:
#       - '{{ .Values.prometheus.config.rule_files | join "\n" }}'

#     alerting:
#       alertmanagers:
#         - static_configs:
#           - targets:
#             - '192.168.49.2:31002'

#   alerts.yml: |
#     groups:
#       - name: stock_alerts
#         rules:
#           - alert: PositivePriceChangeAlert
#             expr: price_change_24h{change_period="24_hours"} > 2
#             for: 1m
#             labels:
#               severity: critical
#             annotations:
#               summary: "Price change percentage for stock is above 2%"
#               description: "The price change percentage for has increased by more than 2% in the last 24 hours."

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: prometheus-deployment
# spec:
#   replicas: {{ .Values.prometheus.replicaCount | default 1 }}
#   selector:
#     matchLabels:
#       app: prometheus
#   template:
#     metadata:
#       labels:
#         app: prometheus
#     spec:
#       containers:
#         - name: prometheus
#           image: "{{ .Values.prometheus.image.repository | default "prom/prometheus" }}:{{ .Values.prometheus.image.tag | default "latest" }}"
#           ports:
#             - containerPort: {{ .Values.prometheus.service.port | default 9090 }}
#           volumeMounts:
#             - name: config-volume
#               mountPath: /etc/prometheus
#               subPath: prometheus.yml
#           args:
#             - "--config.file=/etc/prometheus/prometheus.yml"

#       volumes:
#         - name: config-volume
#           configMap:
#             name: prometheus-config

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-service
# spec:
#   type: {{ .Values.prometheus.service.type | default "NodePort" }}
#   ports:
#     - port: {{ .Values.prometheus.service.port | default 9090 }}
#       targetPort: {{ .Values.prometheus.service.port | default 9090 }}
#       nodePort: {{ .Values.prometheus.service.nodePort | default 30005 }}
#   selector:
#     app: prometheus
