apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Make sure this matches your cluster's storage class



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql  #The label used to match the pods.
  template:
    metadata:
      labels:
        app: mysql  # label to pods
    spec:
      containers:
      - name: mysql
        image: apurvabharambe/database:latest
        env:
        - name: MYSQL_DATABASE
          value: techdemo
        - name: MYSQL_ROOT_PASSWORD
          value: apurva@1234
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc



---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
